function []=Generate_ATPDraw()

% This function generates the Solution.atp file, which can be opened
% directly in ATP without manually creating the cascaded Pi-circuit
% diagram in ATP-Draw. The function uses the RLC parameters obtained
% through VF-PR and NNLS in the modal domain to build the transmission
% lines corresponding to the alpha, beta, and zero modes.

% The implementation is limited to the three-phase 3x3 case.

% Inputs:
%     The function does not require input arguments.

% Outputs:
%     Solution.atp - Executable input file for ATP.


	%                       Reading and variable extraction                  %
	% ─────────────────────────────────────────────────────────────────────────
	Simulation = load('Simulation_data.mat', 'Data');
	Data = Simulation.Data;
	MTL_data_aux = load('Parameter_calculation.mat', 'MTL_data');

	% Number of transmission-line phases after ground-wire elimination
	Nf = nnz(MTL_data_aux.MTL_data(:,1) == 1);

	if Nf ~= 3
		error('ATP file generation is implemented only for the three-phase 3x3 case.');
	end

	% Auxiliary variable calculated in Time_domain_solution
	balance = Data.balance;

	% Number of cascaded Pi circuits
	if isfield(Data.Values_ab0(1),'M')
		M = Data.Values_ab0(1).M;
	else
		M = Data.Fitting_data.M;
	end

	% Alpha-beta mode parameters
	ROAB   = Data.Values_ab0(1).Ro;
	LOAB   = Data.Values_ab0(1).Lo_ATP;
	RAB    = Data.Values_ab0(1).Rk(:);
	LAB    = Data.Values_ab0(1).Lk_ATP(:);
	CKAB   = Data.Values_ab0(1).Ck_ATP;
	CKABIN = CKAB/2;

	% Zero-mode parameters
	RO   = Data.Values_ab0(2).Ro;
	LO   = Data.Values_ab0(2).Lo_ATP;
	R0   = Data.Values_ab0(2).Rk(:);
	L0   = Data.Values_ab0(2).Lk_ATP(:);
	CK   = Data.Values_ab0(2).Ck_ATP;
	CKIN = CK/2;

	% Effective number of RL branches after NNLS
	Np_ab = length(RAB);
	Np_0  = length(R0);
	% ─────────────────────────────────────────────────────────────────────────


	%                        General ATP parameters                         %
	% ─────────────────────────────────────────────────────────────────────────
	% Values defined for the time-domain simulation
	dt_ATP    = Data.Time_data.dt;           % Time step, s
	t_final_ATP = Data.Time_data.t_final;    % Final simulation time, s
	RIN       = Data.Source_values.R_in;     % Source internal resistance, Ohm
	LIN       = Data.Source_values.L_in*1e3; % Source internal inductance, mH
	RL        = Data.Source_values.R_L;      % Load resistance, Ohm
	RT        = 1e7;                         % ATP auxiliary resistance, Ohm

	% Magnitudes and angles of the AC sources in ATP
	V_ATP       = Data.Voltage_values.Vac(1:3);
	Ang_gen_ATP = Data.Voltage_values.General_angle - 90;
	Ang_ATP     = Data.Voltage_values.Angles(1:3) + Ang_gen_ATP;

	% Magnitudes of the DC sources in ATP
	Vdc_ATP     = Data.Voltage_values.Vdc(1:3);
	% ─────────────────────────────────────────────────────────────────────────


	%                        ATP parameter names                            %
	% ─────────────────────────────────────────────────────────────────────────
	ROAB_ATP   = ATP_parameter_name('ROAB');
	RO_ATP     = ATP_parameter_name('RO');
	LOAB_ATP   = ATP_parameter_name('LOAB');
	LO_ATP     = ATP_parameter_name('LO');
	CKAB_ATP   = ATP_parameter_name('CKAB');
	CKABIN_ATP = ATP_parameter_name('CKABIN');
	CK_ATP     = ATP_parameter_name('CK');
	CKIN_ATP   = ATP_parameter_name('CKIN');
	RIN_ATP    = ATP_parameter_name('RIN');
	LIN_ATP    = ATP_parameter_name('LIN');
	RL_ATP     = ATP_parameter_name('RL');
	RT_ATP     = ATP_parameter_name('RT');

	RAB_name = cell(Np_ab,1);
	LAB_name = cell(Np_ab,1);
	RAB_ATP    = cell(Np_ab,1);
	LAB_ATP    = cell(Np_ab,1);

	for k = 1:Np_ab
		RAB_name{k} = sprintf('R%dAB',k);
		LAB_name{k} = sprintf('L%dAB',k);
		RAB_ATP{k}    = ATP_parameter_name(RAB_name{k});
		LAB_ATP{k}    = ATP_parameter_name(LAB_name{k});
	end

	R0_name = cell(Np_0,1);
	L0_name = cell(Np_0,1);
	R0_ATP    = cell(Np_0,1);
	L0_ATP    = cell(Np_0,1);

	for k = 1:Np_0
		R0_name{k} = sprintf('R%d',k);
		L0_name{k} = sprintf('L%d',k);
		R0_ATP{k}    = ATP_parameter_name(R0_name{k});
		L0_ATP{k}    = ATP_parameter_name(L0_name{k});
	end
	% ─────────────────────────────────────────────────────────────────────────


	%                         ATP file creation                              %
	% ─────────────────────────────────────────────────────────────────────────
	fid = fopen('Solution.atp', 'w');

	fprintf(fid,'BEGIN NEW DATA CASE\n');
	fprintf(fid,'C ------------------------------------------------------------------------------\n');
	fprintf(fid,'C Generated by the Matlab code of the cascade Pi circuit\n');
	fprintf(fid,'C This code is developed by Ing. Jose de Jesus Reyes Ramirez\n');
	fprintf(fid,'C Email: jose.reyes0963@alumnos.udg.mx\n');
	fprintf(fid,'C The RLC alpha-beta parameters are computed by RXAB, LXAB and CXAB, and the zero mode are computed by RX, LX and CX.\n');
	fprintf(fid,'C These parameters are calculed by RP-VF and NNLS algorithms, where the passivity constraint is guaranteed.\n');
	fprintf(fid,'C ------------------------------------------------------------------------------\n');
	fprintf(fid,'C  dT  >< Tmax >< Xopt >< Copt ><Epsiln>\n');

	% Time step and final time defined by the user in MATLAB
	dt_ATP_text      = ATP_number_format(dt_ATP);
	t_final_ATP_text = ATP_number_format(t_final_ATP);

	if length(dt_ATP_text) > 8 || length(t_final_ATP_text) > 8
		error('dt or t_final exceeds the eight-character width allowed in the ATP simulation card.');
	end

	fprintf(fid,'%8s%8s                        \n',dt_ATP_text,t_final_ATP_text);
	fprintf(fid,'     500       1       1       1       1       0       0       1       0\n');
	% ─────────────────────────────────────────────────────────────────────────


	%                            $PARAMETER                                    %
	% ─────────────────────────────────────────────────────────────────────────
	fprintf(fid,'$PARAMETER\n');

	% Direct parameter assignment
	fprintf(fid,'%s=%s\n',RIN_ATP,ATP_number_format(RIN));
	fprintf(fid,'%s=%s\n',LIN_ATP,ATP_number_format(LIN));
	fprintf(fid,'%s=%s\n',RL_ATP,ATP_number_format(RL));
	fprintf(fid,'%s=%s\n',RT_ATP,ATP_number_format(RT));

	% Constant parameters of the modal Foster networks
	fprintf(fid,'%s=%s\n',ROAB_ATP,ATP_line_parameter_format(ROAB));

	if balance ~= 1
		fprintf(fid,'%s=%s\n',RO_ATP,ATP_line_parameter_format(RO));

		% Resistances of the zero-mode RL branches
		for k = 1:Np_0
			fprintf(fid,'%s=%s\n',R0_ATP{k},ATP_line_parameter_format(R0(k)));
		end
	end

	% Resistances of the alpha-beta mode RL branches
	for k = 1:Np_ab
		fprintf(fid,'%s=%s\n',RAB_ATP{k},ATP_line_parameter_format(RAB(k)));
	end

	% Inductances of the alpha-beta mode RL branches
	for k = 1:Np_ab
		fprintf(fid,'%s=%s\n',LAB_ATP{k},ATP_line_parameter_format(LAB(k)));
	end

	if balance ~= 1
		% Inductances of the zero-mode RL branches
		for k = 1:Np_0
			fprintf(fid,'%s=%s\n',L0_ATP{k},ATP_line_parameter_format(L0(k)));
		end
	end

	fprintf(fid,'%s=%s\n',LOAB_ATP,ATP_line_parameter_format(LOAB));
	fprintf(fid,'%s=%s\n',CKAB_ATP,ATP_line_parameter_format(CKAB));
	fprintf(fid,'%s=%s\n',CKABIN_ATP,ATP_line_parameter_format(CKABIN));

	if balance ~= 1
		fprintf(fid,'%s=%s\n',LO_ATP,ATP_line_parameter_format(LO));
		fprintf(fid,'%s=%s\n',CK_ATP,ATP_line_parameter_format(CK));
		fprintf(fid,'%s=%s\n',CKIN_ATP,ATP_line_parameter_format(CKIN));
	end

	fprintf(fid,'BLANK $PARAMETER\n');
	% ─────────────────────────────────────────────────────────────────────────


	%                              /BRANCH                                     %
	% ─────────────────────────────────────────────────────────────────────────
	fprintf(fid,'C        1         2         3         4         5         6         7         8\n');
	fprintf(fid,'C 345678901234567890123456789012345678901234567890123456789012345678901234567890\n');
	fprintf(fid,'/BRANCH\n');
	fprintf(fid,'C < n1 >< n2 ><ref1><ref2><       R       ><       L       ><       C       >\n');
	fprintf(fid,'$VINTAGE, 1\n');
    
    fprintf(fid,'C ------------------------------------------------------------------------------\n');
	fprintf(fid,'C C Alpha, Beta and Zero C parameters\n');

	% Output nodes of the inverse Clarke transform
	start_node = {'XX0013','XX0014','XX0015'};

	% First node of each modal transmission line after the RO resistance
	node_after_RO = {'XX0016','XX0017','XX0018'};

	% The first three resistances preserve the ATP-file node numbering
	write_ATP_branch(fid,start_node{1},node_after_RO{1},ROAB_ATP,'R');
	write_ATP_branch(fid,start_node{2},node_after_RO{2},ROAB_ATP,'R');

    if balance ~= 1
		write_ATP_branch(fid,start_node{3},node_after_RO{3},RO_ATP,'R');
    end

	write_ATP_branch(fid,start_node{1},'',CKABIN_ATP,'C');
	write_ATP_branch(fid,start_node{2},'',CKABIN_ATP,'C');

    if balance ~= 1
		write_ATP_branch(fid,start_node{3},'',CKIN_ATP,'C');
    end

	% The counter starts after the reserved nodes XX0016-XX0018.
	node_counter = 18;
	final_node = cell(1,3);

	if balance == 1
		% For a balanced AC source, the zero-mode transmission line is not built.
		% Node XX0015 directly connects both Clarke transforms.
		modes = 1:2;
		final_node{3} = start_node{3};
	else
		modes = 1:3;
	end

	% Modal order: alpha, beta, and zero
	for mode = modes

		if mode <= 2
			LO_mode   = LOAB_ATP;
			RO_mode   = ROAB_ATP;
			R_mode    = RAB_ATP;
			L_mode    = LAB_ATP;
			CK_mode   = CKAB_ATP;
			CKIN_mode = CKABIN_ATP;
			Np_mode   = Np_ab;
		else
			LO_mode   = LO_ATP;
			RO_mode   = RO_ATP;
			R_mode    = R0_ATP;
			L_mode    = L0_ATP;
			CK_mode   = CK_ATP;
			CKIN_mode = CKIN_ATP;
			Np_mode   = Np_0;
		end

		% The first RO resistance of the first section
		current_node = node_after_RO{mode};

		% LO inductance of the first section
		[node_counter,new_node] = new_ATP_node(node_counter);
		write_ATP_branch(fid,current_node,new_node,LO_mode,'L');
		current_node = new_node;

		% Foster branches of the first section
		for k = 1:Np_mode
			[node_counter,new_node] = new_ATP_node(node_counter);
			write_ATP_branch(fid,current_node,new_node,R_mode{k},'R');
			write_ATP_branch(fid,current_node,new_node,L_mode{k},'L');
			current_node = new_node;
		end

		% Output capacitance of the first section
		if M == 1
			write_ATP_branch(fid,current_node,'',CKIN_mode,'C');
		else
			write_ATP_branch(fid,current_node,'',CK_mode,'C');
		end

		% Remaining Pi sections
		for m = 2:M

			% RO resistance
			[node_counter,new_node] = new_ATP_node(node_counter);
			write_ATP_branch(fid,current_node,new_node,RO_mode,'R');
			current_node = new_node;

			% LO inductance
			[node_counter,new_node] = new_ATP_node(node_counter);
			write_ATP_branch(fid,current_node,new_node,LO_mode,'L');
			current_node = new_node;

			% Foster branches Rk || Lk
			for k = 1:Np_mode
				[node_counter,new_node] = new_ATP_node(node_counter);
				write_ATP_branch(fid,current_node,new_node,R_mode{k},'R');
				write_ATP_branch(fid,current_node,new_node,L_mode{k},'L');
				current_node = new_node;
			end

			% Capacitance at the end of the section
			if m == M
				write_ATP_branch(fid,current_node,'',CKIN_mode,'C');
			else
				write_ATP_branch(fid,current_node,'',CK_mode,'C');
			end
		end

		% Terminal node of each modal transmission line
		final_node{mode} = current_node;
	end
	% ─────────────────────────────────────────────────────────────────────────


	%                     Nodes of the returning Clarke transform             %
	% ─────────────────────────────────────────────────────────────────────────
	Clarke_node = cell(1,5);
	for k = 1:5
		[node_counter,Clarke_node{k}] = new_ATP_node(node_counter);
	end
	% ─────────────────────────────────────────────────────────────────────────


	%                           Source impedance                             %
	% ─────────────────────────────────────────────────────────────────────────
	fprintf(fid,'C ------------------------------------------------------------------------------\n');
	fprintf(fid,'C Zs parameters\n');
	write_ATP_branch(fid,'X0001A','XX0002',RIN_ATP,'R');
	write_ATP_branch(fid,'XX0002','XX0005',LIN_ATP,'L');
	write_ATP_branch(fid,'X0001B','XX0003',RIN_ATP,'R');
	write_ATP_branch(fid,'XX0003','XX0006',LIN_ATP,'L');
	write_ATP_branch(fid,'X0001C','XX0004',RIN_ATP,'R');
	write_ATP_branch(fid,'XX0004','XX0007',LIN_ATP,'L');
	% ─────────────────────────────────────────────────────────────────────────


	%                         Auxiliary RT resistances                        %
	% ─────────────────────────────────────────────────────────────────────────
	fprintf(fid,'C ------------------------------------------------------------------------------\n');
	fprintf(fid,'C RT parameters\n');

	% Nodes associated with the inverse Clarke transform
	fixed_RT_nodes = {'XX0005','XX0006','XX0007','XX0008','XX0009','XX0010','XX0011','XX0012'};
	for k = 1:length(fixed_RT_nodes)
		write_ATP_branch(fid,fixed_RT_nodes{k},'',RT_ATP,'R');
	end

	% Terminal nodes of the three modal transmission lines
	for k = 1:3
		write_ATP_branch(fid,final_node{k},'',RT_ATP,'R');
	end

	% Internal nodes of the returning Clarke transform
	for k = 1:5
		write_ATP_branch(fid,Clarke_node{k},'',RT_ATP,'R');
	end

	% Load resistances in the phase domain
	write_ATP_branch(fid,'PHASEA','',RL_ATP,'R');
	write_ATP_branch(fid,'PHASEB','',RL_ATP,'R');
	write_ATP_branch(fid,'PHASEC','',RL_ATP,'R');
	% ─────────────────────────────────────────────────────────────────────────

	% Return to the normal format after the RLC branches
	fprintf(fid,'$VINTAGE, 0\n');


	%                               /SWITCH                                    %
	% ─────────────────────────────────────────────────────────────────────────
	fprintf(fid,'/SWITCH\n');
	fprintf(fid,'C < n 1>< n 2>< Tclose ><Top/Tde ><   Ie   ><Vf/CLOP ><  type  >\n');
	% ─────────────────────────────────────────────────────────────────────────


	%                                /SOURCE                                   %
	% ─────────────────────────────────────────────────────────────────────────
	fprintf(fid,'/SOURCE\n');
	fprintf(fid,'C < n 1><>< Ampl.  >< Freq.  ><Phase/T0><   A1   ><   T1   >< TSTART >< TSTOP  >\n');

	% Inverse Clarke transform: abc -> alpha, beta, zero
	fprintf(fid,'14XX0005      1.E-20       60.                                     -1.       10.\n');
	fprintf(fid,'18XX0008  .816496581XX0013      \n');
	fprintf(fid,'14XX0006      1.E-20       60.                                     -1.       10.\n');
	fprintf(fid,'18XX0009   .40824829      XX0013\n');
	fprintf(fid,'14XX0007      1.E-20       60.                                     -1.       10.\n');
	fprintf(fid,'18XX0010   .40824829      XX0013\n');
	fprintf(fid,'14XX0009      1.E-20       60.                                     -1.       10.\n');
	fprintf(fid,'18XX0011  .707106781XX0014  \n');
	fprintf(fid,'14XX0010      1.E-20       60.                                     -1.       10.\n');
	fprintf(fid,'18XX0012  .707106781      XX0014\n');
	fprintf(fid,'14XX0008      1.E-20       60.                                     -1.       10.\n');
	fprintf(fid,'18        .577350269XX0015      \n');
	fprintf(fid,'14XX0011      1.E-20       60.                                     -1.       10.\n');
	fprintf(fid,'18        .577350269XX0015 \n');
	fprintf(fid,'14XX0012      1.E-20       60.                                     -1.       10.\n');
	fprintf(fid,'18        .577350269XX0015 \n');

	% Three-phase voltage sources
	if Data.Source_type == 1
		% Source_type AC
		fprintf(fid,'14X0001A%12s%10s%10s%37s10.\n',ATP_number_format(V_ATP(1)), ...
			ATP_number_format(60),ATP_number_format(Ang_ATP(1)),'');
		fprintf(fid,'14X0001B%12s%10s%10s%37s10.\n',ATP_number_format(V_ATP(2)), ...
			ATP_number_format(60),ATP_number_format(Ang_ATP(2)),'');
		fprintf(fid,'14X0001C%12s%10s%10s%37s10.\n',ATP_number_format(V_ATP(3)), ...
			ATP_number_format(60),ATP_number_format(Ang_ATP(3)),'');
	elseif Data.Source_type == 2
		% Source_type DC
		fprintf(fid,'11X0001A 0%10s%47s-1.%6s1.E3\n',ATP_number_format(Vdc_ATP(1)),'','');
		fprintf(fid,'11X0001B 0%10s%47s-1.%6s1.E3\n',ATP_number_format(Vdc_ATP(2)),'','');
		fprintf(fid,'11X0001C 0%10s%47s-1.%6s1.E3\n',ATP_number_format(Vdc_ATP(3)),'','');
	else
		error('Invalid source type. Use 1 for AC or 2 for DC.');
	end

	% Clarke transform: alpha, beta, zero -> abc
	% final_node{1}: alpha, final_node{2}: beta, final_node{3}: zero
	fprintf(fid,'14%s      1.E-20       60.                                     -1.       10.\n',final_node{1});
	fprintf(fid,'18%s  .816496581PHASEA      \n',Clarke_node{1});
	fprintf(fid,'14%s      1.E-20       60.                                     -1.       10.\n',final_node{3});
	fprintf(fid,'18%s  .577350269PHASEA      \n',Clarke_node{4});
	fprintf(fid,'14%s      1.E-20       60.                                     -1.       10.\n',final_node{2});
	fprintf(fid,'18%s  .707106781PHASEB      \n',Clarke_node{3});
	fprintf(fid,'14%s      1.E-20       60.                                     -1.       10.\n',Clarke_node{4});
	fprintf(fid,'18%s  .577350269PHASEB      \n',Clarke_node{5});
	fprintf(fid,'14%s      1.E-20       60.                                     -1.       10.\n',Clarke_node{5});
	fprintf(fid,'18        .577350269PHASEC      \n');
	fprintf(fid,'14%s      1.E-20       60.                                     -1.       10.\n',Clarke_node{3});
	fprintf(fid,'18        .707106781      PHASEC\n');
	fprintf(fid,'14%s      1.E-20       60.                                     -1.       10.\n',Clarke_node{2});
	fprintf(fid,'18         .40824829      PHASEC\n');
	fprintf(fid,'14%s      1.E-20       60.                                     -1.       10.\n',Clarke_node{1});
	fprintf(fid,'18%s   .40824829      PHASEB\n',Clarke_node{2});
	% ─────────────────────────────────────────────────────────────────────────


	%                                /OUTPUT                                   %
	% ─────────────────────────────────────────────────────────────────────────
	fprintf(fid,'/OUTPUT\n');
	fprintf(fid,'  PHASEAPHASEBPHASEC\n');
	fprintf(fid,'BLANK BRANCH\n');
	fprintf(fid,'BLANK SWITCH\n');
	fprintf(fid,'BLANK SOURCE\n');
	fprintf(fid,'BLANK OUTPUT\n');
	fprintf(fid,'BLANK PLOT\n');
	fprintf(fid,'BEGIN NEW DATA CASE\n');
	fprintf(fid,'BLANK\n');
	% ─────────────────────────────────────────────────────────────────────────

	fclose(fid);
	disp('****Solution.atp created successfully.');

end


function ATP_name = ATP_parameter_name(name)

	if length(name) > 16
		error('The parameter name "%s" exceeds the sixteen characters allowed in /BRANCH.',name);
	end

	ATP_name = [name repmat('_',1,16-length(name))];

end


function [node_counter,node] = new_ATP_node(node_counter)

	node_counter = node_counter + 1;

	if node_counter > 9999
		error('The maximum number of nodes, XX9999, was exceeded.');
	end

	node = sprintf('XX%04d',node_counter);

end


function write_ATP_branch(fid,node1,node2,parameter,element_type)

	line = repmat(' ',1,80);

	if length(node1) ~= 6
		error('Node "%s" does not contain six characters.',node1);
	end

	line(3:8) = node1;

	if ~isempty(node2)
		if length(node2) ~= 6
			error('Node "%s" does not contain six characters.',node2);
		end
		line(9:14) = node2;
	end

	if length(parameter) ~= 16
		error('Parameter "%s" does not contain sixteen characters.',parameter);
	end

	switch upper(element_type)
		case 'R'
			line(27:42) = parameter;
		case 'L'
			line(43:58) = parameter;
		case 'C'
			line(59:74) = parameter;
	end

	line(80) = '0';
	fprintf(fid,'%s\n',line);

end

function text = ATP_line_parameter_format(value)

	text = sprintf('%.15E',value);

end


function text = ATP_number_format(value)

	text = sprintf('%.15G',value);

	if ~contains(text,'.')
		idx = regexp(text,'[Ee]','once');

		if isempty(idx)
			text = [text '.'];
		else
			text = [text(1:idx-1) '.' text(idx:end)];
		end
	end

end