function [Phase_voltages, Data, Matrices] = Time_domain_solution()

% This function performs the transmission-line simulation in
% the time domain using three methodologies: state-space
% representation, an EMT-type formulation, and the Numerical Laplace
% Transform (NLT).

% Inputs:
%     The function does not require input arguments.

% Outputs:
%     Phase_voltages - Structure containing the voltages obtained in the
%                      phase domain using the selected solution methods
%     Data           - Structure with the parameters used in the simulation
%     Matrices       - Structure with the matrices generated by the
%                      state-space and EMTP-type solutions


	%                       Reading and variable extraction                  %
	% ─────────────────────────────────────────────────────────────────────────
	Data = load('Simulation_parameters.mat', 'Values_ab0', 'Fitting_data');
	MTL_data_aux = load('Parameter_calculation.mat', 'MTL_data');

	% Number of transmission-line phases after ground-wire elimination
	Nf = nnz(MTL_data_aux.MTL_data(:,1) == 1);

	if Nf ~= 3 && Nf ~= 6
		error('The time-domain simulation is implemented only for 3- or 6-phase cases.');
	end
	% ─────────────────────────────────────────────────────────────────────────


	%                         General simulation data                         %
	% ─────────────────────────────────────────────────────────────────────────
	% Time parameters for the different solutions
	Data.Time_data.dt          = 1e-6; % Time step
	Data.Time_data.t_final     = 0.02; % Final simulation time
	Data.Time_data.t_final_NLT = 0.02; % Final simulation time NLT

	% Equivalent-source and load parameters
	Data.Source_values.R_in = 0.5;   % Source resistance
	Data.Source_values.L_in = 30e-3; % Source inductance
	Data.Source_values.R_L  = 1e6;   % Load resistance

	% Source type
	Data.Source_type = 1; % 1 = V_ac, 2 = V_dc

	% AC-source voltage magnitudes
	Data.Voltage_values.Vac = [1; 1; 1];

	% Individual phase angles of the AC-source voltages
	Data.Voltage_values.Angles = [0; -120; 120];

	% General phase-angle shift used in ATP
	Data.Voltage_values.General_angle = 90;

	% DC-source voltage magnitudes
	Data.Voltage_values.Vdc = [1; 1; 1];

	% Solution methods and algorithms
	Data.Solution_method    = 1; % 1.- All  2.- SS  3.- EMT  4.- NLT
	Data.SS_solution_type   = 2; % 1.- Normal  2.- Optimized (sparse)
	Data.EMTP_solution_type = 1; % 1.- Thomas Algorithm  2.- inv(Gm)*H
	Data.NLT_window         = 3; % 1.- Hanning  2.- Wilcox  3.- Blackman  4.- Riesz  5.- Lanczos
	Data.NLT_damping        = 1; % 1.- c=2*dw  2.- c=log(N^2)/T

	% Editor used to modify the default values before the simulation
	[Data, ok] = Time_simulation_editor(Data);

	if ~ok
		error('The time-domain simulation configuration was canceled.');
	end

	% Methods selected for the simulation
	run_SS   = Data.Solution_method == 1 || Data.Solution_method == 2;
	run_EMT  = Data.Solution_method == 1 || Data.Solution_method == 3;
	run_NLT  = Data.Solution_method == 1 || Data.Solution_method == 4;

	% Output-structure initialization
	Phase_voltages = struct();
	Matrices = struct();

	if Nf == 6
		Data.Voltage_values.Vac = [Data.Voltage_values.Vac; Data.Voltage_values.Vac];
		Data.Voltage_values.Angles = [Data.Voltage_values.Angles; Data.Voltage_values.Angles];
		Data.Voltage_values.Vdc = [Data.Voltage_values.Vdc; Data.Voltage_values.Vdc];
	end

	% Construction of the time vectors for SS, EMT, and NLT
	Data.Time_data.t = 0:Data.Time_data.dt:Data.Time_data.t_final-Data.Time_data.dt;
	Data.Time_data.N = length(Data.Time_data.t);
	Data.Time_data.t2 = 0:Data.Time_data.dt:Data.Time_data.t_final_NLT-Data.Time_data.dt;
	Data.Time_data.N2 = length(Data.Time_data.t2);
	% ─────────────────────────────────────────────────────────────────────────


	%                    Additional simulation configuration                  %
	% ─────────────────────────────────────────────────────────────────────────
	% Determination of whether the zero modes need to be calculated
	if Data.Source_type == 1
		% Equal magnitudes
		balanced_magnitudes = all(Data.Voltage_values.Vac == Data.Voltage_values.Vac(1));

		if Nf == 3
			% 120° phase shift among the three phases
			balanced_angles = mod(Data.Voltage_values.Angles(1) - Data.Voltage_values.Angles(2),360) == 120 && ...
						      mod(Data.Voltage_values.Angles(2) - Data.Voltage_values.Angles(3),360) == 120;

		elseif Nf == 6
			% 120° phase shift in both circuits
			balanced_angles = mod(Data.Voltage_values.Angles(1) - Data.Voltage_values.Angles(2),360) == 120 && ...
						      mod(Data.Voltage_values.Angles(2) - Data.Voltage_values.Angles(3),360) == 120 && ...
						      mod(Data.Voltage_values.Angles(4) - Data.Voltage_values.Angles(5),360) == 120 && ...
						      mod(Data.Voltage_values.Angles(5) - Data.Voltage_values.Angles(6),360) == 120;
		end

		if balanced_magnitudes && balanced_angles
			Data.balance = 1; % Balanced source; the zero modes are not calculated
		else
			Data.balance = 0; % Unbalanced source; the zero modes are calculated
		end

	elseif Data.Source_type == 2
		Data.balance = 2; % DC source; the zero modes are calculated

	else
		Data.balance = 0;

	end


	% Clarke transform according to the number of phases
	if Nf == 3

		% Clarke transform for a three-phase transmission line
		TClarke = sqrt(2/3) * [   1         0       1/sqrt(2)
								-1/2    sqrt(3)/2   1/sqrt(2)
								-1/2   -sqrt(3)/2   1/sqrt(2)];

	elseif Nf == 6

		% Clarke transform for a double-circuit three-phase transmission line
		TClarke = [-1/sqrt(6)  1/sqrt(2)   1/sqrt(6)   1/sqrt(6)        0            0
					2/sqrt(6)      0       1/sqrt(6)   1/sqrt(6)        0            0
				   -1/sqrt(6) -1/sqrt(2)   1/sqrt(6)   1/sqrt(6)        0            0
						0          0      -1/sqrt(6)   1/sqrt(6)    1/sqrt(2)    -1/sqrt(6)
						0          0      -1/sqrt(6)   1/sqrt(6)        0         2/sqrt(6)
						0          0      -1/sqrt(6)   1/sqrt(6)   -1/sqrt(2)    -1/sqrt(6)];

	end

	% Inverse modal-transformation matrix
	TClarke_inv = inv(TClarke);
	% ─────────────────────────────────────────────────────────────────────────


	%                  Transformation of voltages to modal domain             %
	% ─────────────────────────────────────────────────────────────────────────
	[Modal_voltages_data] = Modal_voltages(Data.Source_type, Data.Time_data.t, Data.Voltage_values);

	if Nf == 3
		% Modal order: alpha, beta, zero
		mode_voltages = {Modal_voltages_data.V_alpha, Modal_voltages_data.V_beta, Modal_voltages_data.V_zero};
		parameter_index = [1 1 2];
		zero_mode_indices = 3;

	elseif Nf == 6
		% Modal order: alpha1, beta1, zero1, zero2, beta2, alpha2
		mode_voltages = {Modal_voltages_data.V_alpha, Modal_voltages_data.V_beta, Modal_voltages_data.V_zero, ...
				   Modal_voltages_data.V_zero2, Modal_voltages_data.V_beta2, Modal_voltages_data.V_alpha2};
		parameter_index = [1 1 2 3 1 1];
		zero_mode_indices = [3 4];
	end
	% ─────────────────────────────────────────────────────────────────────────

 
	%                    Source voltages in the phase domain                  %
	% ─────────────────────────────────────────────────────────────────────────
	modal_source_voltages = vertcat(mode_voltages{:});
	Phase_voltages.source = TClarke_inv\modal_source_voltages;
	% ─────────────────────────────────────────────────────────────────────────


	% ─────────────────────────────────────────────────────────────────────────
	%                             Passivity test                            
	% ─────────────────────────────────────────────────────────────────────────
	if Data.passivity_test == 1

		% The matrices for the passivity test are constructed.
		Passivity_matrices = struct();

		for k = 1:Nf

			p = parameter_index(k);

			Data.Passivity_data(k) = struct('dt',Data.Time_data.dt,'N',Data.Time_data.N,...
			'M',Data.Values_ab0(1).M,'Ro',Data.Values_ab0(p).Ro,'Rk',Data.Values_ab0(p).Rk,...
			'Lo',Data.Values_ab0(p).Lo,'Lk',Data.Values_ab0(p).Lk,'Ck',Data.Values_ab0(p).Ck,...
			'G',Data.Values_ab0(p).G,'R_in',Data.Source_values.R_in,'L_in',Data.Source_values.L_in,...
			'R_L',Data.Source_values.R_L,'V',mode_voltages{k},'t',Data.Time_data.t);

			[Passivity_matrices.SS_matrix(k), Passivity_matrices.SS_m(k), ...
			 Passivity_matrices.SS_m2(k), Passivity_matrices.SS_m3(k)] = ...
		     State_space_matrices_for_passivity(Data.Passivity_data(k));

		end

		% Saving the matrices for the passivity test.
		save('Passivity_matrices.mat','Passivity_matrices','Data');

		% Passivity-test calculation.
		Passivity_test();

	end
	% ─────────────────────────────────────────────────────────────────────────


	% ─────────────────────────────────────────────────────────────────────────
	%                               State space                          
	% ─────────────────────────────────────────────────────────────────────────
	if run_SS

		%                    Data for the state-space solution                    %
		% ─────────────────────────────────────────────────────────────────────────
		% One transmission line is constructed for each propagation mode.
		for k = 1:Nf

			p = parameter_index(k);

			Data.SS_data(k) = struct('dt',Data.Time_data.dt,'N',Data.Time_data.N,'M',Data.Values_ab0(1).M,'Ro',...
			Data.Values_ab0(p).Ro,'Rk',Data.Values_ab0(p).Rk,'Lo',Data.Values_ab0(p).Lo,'Lk',Data.Values_ab0(p).Lk,...
			'Ck',Data.Values_ab0(p).Ck,'G',Data.Values_ab0(p).G,'R_in',Data.Source_values.R_in,'L_in',...
			Data.Source_values.L_in,'R_L',Data.Source_values.R_L,'V',mode_voltages{k},'t',Data.Time_data.t);

		end
		% ─────────────────────────────────────────────────────────────────────────


		%                          State-space solution                           %
		% ─────────────────────────────────────────────────────────────────────────
		% Modal-voltage matrix
		V_ab0_SS = zeros(Nf,Data.Time_data.N);

		for k = 1:Nf

			if Data.balance == 1 && any(k == zero_mode_indices)
				% For a balanced AC source, the zero mode does not need to be solved
				V_ab0_SS(k,:) = zeros(1,Data.Time_data.N);
			else
				if Data.SS_solution_type == 1
					[Matrices.SS_matrix(k), Matrices.SS_m(k), Matrices.SS_m2(k), Matrices.SS_m3(k), V_ab0_SS(k,:)] = ...
						State_space_solution(Data.SS_data(k));
				elseif Data.SS_solution_type == 2
					[Matrices.SS_matrix(k), Matrices.SS_m(k), Matrices.SS_m2(k), Matrices.SS_m3(k), V_ab0_SS(k,:)] = ...
						Sparse_state_space_solution(Data.SS_data(k));
				else
					error('Invalid state-space solution type.');
				end
			end

		end
		% ─────────────────────────────────────────────────────────────────────────


		%                    SS modal voltages in the time domain                 %
		% ─────────────────────────────────────────────────────────────────────────
		Phase_voltages.SS = TClarke_inv\V_ab0_SS;
		% ─────────────────────────────────────────────────────────────────────────
	end


	% ─────────────────────────────────────────────────────────────────────────
	%                            EMT-type solution                           
	% ─────────────────────────────────────────────────────────────────────────
	if run_EMT


		%                      Data for the EMT-type solution                     %
		% ─────────────────────────────────────────────────────────────────────────
		% An independent structure is constructed for each propagation mode.
		for k = 1:Nf

			p = parameter_index(k);

			Data.EMT_data(k) = struct('t',Data.Time_data.t,'dt',Data.Time_data.dt,'N',Data.Time_data.N,...
			'n',Data.Values_ab0(1).M,'Ro',Data.Values_ab0(p).Ro,'Rk',Data.Values_ab0(p).Rk,'Lo',...
			Data.Values_ab0(p).Lo,'Lk',Data.Values_ab0(p).Lk,'Ck',Data.Values_ab0(p).Ck,'G',Data.Values_ab0(p).G,...
			'R_in',Data.Source_values.R_in,'L_in',Data.Source_values.L_in,'R_L',Data.Source_values.R_L,'V',...
			mode_voltages{k},'solution_type',Data.EMT_solution_type);

		end
		% ─────────────────────────────────────────────────────────────────────────


		%                           EMT-type solution                           %
		% ─────────────────────────────────────────────────────────────────────────
		% Modal-voltage matrix
		V_ab0_EMT = zeros(Nf,Data.Time_data.N);

		for k = 1:Nf

			if Data.balance == 1 && any(k == zero_mode_indices)
				% For a balanced AC source, the zero mode does not need to be solved
				V_ab0_EMT(k,:) = zeros(1,Data.Time_data.N);
			else
				[Matrices.G_EMT_matrix(k), V_ab0_EMT(k,:)] = EMT_solution(Data.EMT_data(k));
			end

		end
		% ─────────────────────────────────────────────────────────────────────────


		%                   EMTP modal voltages in the time domain               %
		% ─────────────────────────────────────────────────────────────────────────
		Phase_voltages.EMT = TClarke_inv\V_ab0_EMT;
		% ─────────────────────────────────────────────────────────────────────────
	end


	% ─────────────────────────────────────────────────────────────────────────
	%                             NLT solution                          
	% ─────────────────────────────────────────────────────────────────────────
	if run_NLT

		
		%                             Data for NLT                              %
		% ─────────────────────────────────────────────────────────────────────────
		% Structure with the simulation parameters, AC/DC source, and load.
		Data.NLT_data = struct('Source_type',Data.Source_type,'dt',Data.Time_data.dt,'t_final',Data.Time_data.t_final_NLT,...
		't',Data.Time_data.t2,'N',Data.Time_data.N2,'Vac',Data.Voltage_values.Vac,'Vdc',Data.Voltage_values.Vdc,...
		'R_in',Data.Source_values.R_in,'L_in',Data.Source_values.L_in,'R_L',Data.Source_values.R_L,...
		'Angles',Data.Voltage_values.Angles,'General_angle',Data.Voltage_values.General_angle,'Window',Data.NLT_window,...
		'Damping',Data.NLT_damping);
		% ─────────────────────────────────────────────────────────────────────────


		%                            NLT solution                               %
		% ─────────────────────────────────────────────────────────────────────────
		[Phase_voltages.V_NLT] = Multiphase_NLT_solution(Data.NLT_data);
		% ─────────────────────────────────────────────────────────────────────────
	end
	
	% Data storage
	save('Simulation_data.mat', 'Data');

	% ─────────────────────────────────────────────────────────────────────────
	%                                  Plots                                 
	% ─────────────────────────────────────────────────────────────────────────
	if Nf == 3


		%                 Comparison of selected methods: 3 phases               %
		% ─────────────────────────────────────────────────────────────────────────
		figure;
		hold on;
		h = gobjects(0);
		labels = {};

		if run_NLT
			h(end+1) = plot(nan,nan,'k');
			labels{end+1} = 'NLT';
			for k = 1:3
				plot(Data.Time_data.t2,Phase_voltages.V_NLT(k,:),'k','HandleVisibility','off');
			end
		end

		if run_SS
			h(end+1) = plot(nan,nan,'r','LineStyle','-.');
			labels{end+1} = 'SS';
			for k = 1:3
				plot(Data.Time_data.t,Phase_voltages.SS(k,:),'r','LineStyle','-.','HandleVisibility','off');
			end
		end

		if run_EMT
			h(end+1) = plot(nan,nan,'b','LineStyle','--');
			labels{end+1} = 'EMT';
			for k = 1:3
				plot(Data.Time_data.t,Phase_voltages.EMT(k,:),'b','LineStyle','--','HandleVisibility','off');
			end
		end

		xlabel('Time [s]');
		ylabel('Magnitude [p.u.]');
		legend(h,labels);
		ylim([-2.5 2.5]);
		% ─────────────────────────────────────────────────────────────────────────

	elseif Nf == 6

		%                 Comparison of selected methods: 6 phases               %
		% ─────────────────────────────────────────────────────────────────────────
		figure;

		% Circuit 1: phases a, b, and c
		subplot(2,1,1);
		hold on;
		h = gobjects(0);
		labels = {};

		if run_NLT
			h(end+1) = plot(nan,nan,'k');
			labels{end+1} = 'NLT';
			for k = 1:3
				plot(Data.Time_data.t2,Phase_voltages.V_NLT(k,:),'k','HandleVisibility','off');
			end
		end
		if run_SS
			h(end+1) = plot(nan,nan,'r','LineStyle','-.');
			labels{end+1} = 'SS';
			for k = 1:3
				plot(Data.Time_data.t,Phase_voltages.SS(k,:),'r','LineStyle','-.','HandleVisibility','off');
			end
		end
		if run_EMT
			h(end+1) = plot(nan,nan,'b','LineStyle','--');
			labels{end+1} = 'EMT';
			for k = 1:3
				plot(Data.Time_data.t,Phase_voltages.EMT(k,:),'b','LineStyle','--','HandleVisibility','off');
			end
		end

		xlabel('Time [s]');
		ylabel('Magnitude [p.u.]');
		title('Circuit 1');
		legend(h,labels);
		ylim([-2.5 2.5]);

		% Circuit 2: phases a, b, and c
		subplot(2,1,2);
		hold on;
		h = gobjects(0);
		labels = {};

		if run_NLT
			h(end+1) = plot(nan,nan,'k');
			labels{end+1} = 'NLT';
			for k = 4:6
				plot(Data.Time_data.t2,Phase_voltages.V_NLT(k,:),'k','HandleVisibility','off');
			end
		end
		if run_SS
			h(end+1) = plot(nan,nan,'r','LineStyle','-.');
			labels{end+1} = 'SS';
			for k = 4:6
				plot(Data.Time_data.t,Phase_voltages.SS(k,:),'r','LineStyle','-.','HandleVisibility','off');
			end
		end
		if run_EMT
			h(end+1) = plot(nan,nan,'b','LineStyle','--');
			labels{end+1} = 'EMT';
			for k = 4:6
				plot(Data.Time_data.t,Phase_voltages.EMT(k,:),'b','LineStyle','--','HandleVisibility','off');
			end
		end

		xlabel('Time [s]');
		ylabel('Magnitude [p.u.]');
		title('Circuit 2');
		legend(h,labels);
		ylim([-2.5 2.5]);
		% ─────────────────────────────────────────────────────────────────────────
	end

end